export class Persona {
    constructor (
        public ApellidoyNombre: string,
        public Dni: string,
        public FechaNacimiento?: string,
        public Sexo?: string,
        public EstadoCivil?: string,
        public Nacionalidad?: string,
        public ID?: string,
        public IDSindicato?: string,
        public Domicilio?: string,
        public email?: string,
        public CodPostal?: string,
        public Localidad?: string,
        public Provincia?: string,
        public Celular?: string,
        public TEFijo?: string,
        public FechaIngresoASindicato?: string,
        public Tipo?: string,
        public Ficha?: string,
        public CuilCuit?: string,
        public Social?: string,
        public Foto?: string,
        public DateAdd?: string,
        public puser?: string,
        public DateUpd?: string,
        public UserUpd?: string,
        public DateDel?: string,
        public UserDel?: string
    ) { }
    }
